# Generated by Django 2.2.6 on 2020-06-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancar', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='process',
            field=models.ManyToManyField(related_name='carts', to='pancar.Process'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
