# Generated by Django 2.2.6 on 2020-06-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancar', '0005_auto_20200615_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.DateTimeField(null=True),
        ),
    ]
