# Generated by Django 3.1 on 2020-08-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancar', '0008_auto_20200807_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
