# Generated by Django 3.1 on 2020-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancar', '0009_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='insurance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='review_date',
            field=models.DateField(null=True),
        ),
    ]
