# Generated by Django 2.2.6 on 2020-04-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pancar', '0003_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pancar.Klient'),
        ),
    ]
