# Generated by Django 2.2.6 on 2020-04-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pancar', '0004_auto_20200421_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='date',
        ),
        migrations.RemoveField(
            model_name='process',
            name='description',
        ),
    ]
