# Generated by Django 2.2.6 on 2020-06-08 09:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('pancar', '0009_auto_20200607_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Klient',
        ),
    ]
